name: Release Artifacts

on:
  workflow_dispatch:
    inputs:
      release-major-tag:
        description: 'Whether to create major tag of docker image or not. This will create a tag such as 2.3 which points to this version.'
        required: true
        type: boolean
      release-latest-tag:
        description: >
          'Whether to create latest tag of docker image or not. This will update the latest tag to point to this version. You should set this when releasing the latest version, but not patches to old versions.'
        required: true
        type: boolean

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout Data Prepper
      uses: actions/checkout@v2
    - name: Check inputs
      run : 
    - name: Get Version
      run:  grep '^version=' gradle.properties >> $GITHUB_ENV

    - name: Create Release Description
      run: |
        echo 'version: ${{ env.version }}' > release-description.yaml
        echo 'build_number: ${{ github.run_number }}' >> release-description.yaml
        echo 'release_major_tag: ${{ github.event.inputs.release-major-tag }}' >> release-description.yaml
        echo 'release_latest_tag: ${{ github.event.inputs.release-latest-tag }}' >> release-description.yaml

    - name: Create tag
      uses: actions/github-script@v6
      with:
        github-token: ${{ github.TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ env.version }}',
            sha: context.sha
          })

    - name: Draft release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        name: '${{ env.version }}'
        tag_name: 'refs/tags/${{ env.version }}'
        files: |
          release-description.yaml
